(define (bigger x y z) (if (> x y)
                           (if (> y z)
                               (+ x y)
                               (+ x z))
                           (if (> x z)
                               (+ x y)
                               (+ y z))))
(bigger 1 2 3)
(bigger 1 3 2)
(bigger 3 2 1)
(bigger 3 1 2)
(bigger 2 1 3)
(bigger 2 3 1)
