(define (sum-of-two-max x y z)
  (if (> x y)
   (if (> y z)
     (+ x y)
     (+ x z))
   (if (> x z)
     (+ x y)
     (+ y z))))

(sum-of-two-max 1 2 3)
;(sum-of-two-max 1 3 2)
;(sum-of-two-max 3 2 1)
;(sum-of-two-max 3 1 2)
;(sum-of-two-max 2 1 3)
;(sum-of-two-max 2 3 1)
